# Generated by Django 5.2.6 on 2025-10-14 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['institution__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('floors', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='orgs.campus')),
            ],
            options={
                'ordering': ['campus__institution__name', 'campus__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='campus',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campuses', to='orgs.institution'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Rooms', to='orgs.building')),
            ],
            options={
                'ordering': ['building__campus__institution__name', 'building__campus__name', 'building__name', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['campus', 'code'], name='orgs_buildi_campus__4af39e_idx'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('campus', 'code'), name='uq_building_campus_code'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('campus', 'name'), name='uq_building_campus_name'),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['institution', 'code'], name='orgs_campus_institu_4debd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uq_campus_institution_code'),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='uq_campus_institution_name'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building', 'code'], name='orgs_room_buildin_86288d_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building', 'code'), name='uq_room_building_code'),
        ),
    ]
